### ISSUE TITLE
missing module?

### ISSUE THREAD

**Issue by xeiki** [Murgeye/teamspeak3-python-bot#1]
Hi, I'm getting this error on file TS3Connection.py if I run main.py:

`Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    import Bot
  File "/root/teamspeak3-python-bot/Bot.py", line 1, in <module>
    import ts3.TS3Connection
  File "/root/teamspeak3-python-bot/ts3/TS3Connection.py", line 8, in <module>
    import blinker
ImportError: No module named 'blinker'`

I did enclose the blinker module but Ithink it should be better if it runs?
Where can I get this module?
How can I solve this problem?

**Comment by Murgeye** [comment]
Hi eikichi87,

you should be able to install blinker with pip. (Try using `pip3 install blinker`)
I have added a requirements.txt to the api repository for others who run into the same problem and will
add a note in the README.
