### ISSUE TITLE
Having Trouble with Calling Functions and Variables from Modules / other py files

### ISSUE THREAD

**Issue by gccalvin** [Murgeye/teamspeak3-python-bot#10]
Hello,
I am trying to call functions and variables that are declared in another .py file. Usually I believe this is done with import and from. However, I am having difficulty as this uses a module loader (which may be causing the issue?). I have attached some images to explain my test environment.

I declared a variable, "name," on a moduletest1.py. It looks like  < name = "Bob" > (no <>). On moduletest2.py, I tried to print that variable. I tested with and without the Moduleloader, and have been unsuccessful. Inside the moduleloader log file, it says that the module "moduletest1" loaded successfully. However, in the eventhandler "name" is undefined. I've also tried without the moduleloader and just using "from moduletest1 import *" and the print function still doesn't work.

Am I doing something wrong? I haven't been using python that long, so a lot of these concepts are still new to me.

![configini](https://user-images.githubusercontent.com/17185709/96840288-dbd27580-140f-11eb-8c66-f75c6b18e76f.png)
![eventhandlerlog](https://user-images.githubusercontent.com/17185709/96840289-dc6b0c00-140f-11eb-8793-1dd003a9a77c.png)
![moduleloader](https://user-images.githubusercontent.com/17185709/96840291-dc6b0c00-140f-11eb-9080-42c3fd3283cd.png)
![moduleloaderlogusingfromimport](https://user-images.githubusercontent.com/17185709/96840293-dc6b0c00-140f-11eb-872a-2302d4bce6a7.png)
![moduletest2](https://user-images.githubusercontent.com/17185709/96840294-dc6b0c00-140f-11eb-800b-0cd4eb8ead76.png)
![output](https://user-images.githubusercontent.com/17185709/96840295-dd03a280-140f-11eb-8c8b-152cd8bfa7f7.png)

Thank you for your time and effort,
gccalvin

**Comment by Murgeye** [comment]
Hey gccalvin,

local imports are always a bit of a mess in python, sadly. I'll try to explain this as good as I can.

You can only import modules from your import path, which you can determine via this snippet:
```
import sys
print(sys.path)
```
For me, this returns (when run from main.py):
```
['/home/fabian/Stuff/teamspeak3-python-bot', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/fabian/.local/lib/python3.8/site-packages', '/usr/lib/python3.8/site-packages']
```
As you can see, this does not contain the modules path but only the current working directory, which is why you cannot do `import moduletest`

You should, however, be able to do `import modules.moduletest`.

So this is what works for me:

modules/testmodule.py:
```
#! /usr/bin/env python

testvar = "asdf"
```

modules/testmodule2.py:
```
#! /usr/bin/env python

from modules.testmodule import *
import Moduleloader
import Bot
import logging
from ts3.TS3Connection import TS3QueryException
bot = None
logger = logging.getLogger("bot")


@Moduleloader.setup
def setup(ts3bot):
    global bot
    bot = ts3bot
    print("Module loaded")
    print(testvar)

@Moduleloader.command("printvar")
def printvar(sender, msg):
    print("Command called")
    print(testvar)
```

Result:
```
$ python3 main.py
Module loaded
asdf
Command called
asdf
```

Does this help you?

**Comment by gccalvin** [comment]
Thanks for the explanation, it works now!

Do you have a donation page?

**Comment by Murgeye** [comment]
> Thanks for the explanation, it works now!

Great, if you have anymore questions, feel free to ask them, always love when somebody actually uses one of my projects!

> Do you have a donation page?

Thanks for the offer, but we don't take any donations, as we do not need them. This is essentially a project we do for fun in our free time (and that by now is pretty low-maintenance).
