### ISSUE TITLE
ImportError: No module named 'ts3.TS3Connection'

### ISSUE THREAD

**Issue by julianng03** [Murgeye/teamspeak3-python-bot#3]
Hello, when I started bot i have error: ImportError: No module named 'ts3.TS3Connection'

All logs:
> Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    import Bot
  File "/home/teamspeak3-python-bot-master/Bot.py", line 1, in <module>
    import ts3.TS3Connection
ImportError: No module named 'ts3.TS3Connection'
> 
I have ts3 (pip3 install ts3)

**Comment by Murgeye** [comment]
Hey,

did you follow the README? Especially this part:

> 
>
>**Getting the bot**
>
>1. Clone this repository
>2. Update the ts3API submodule by running git submodule update --init --recursive in the directory created in 1
>3. Install dependencies for the api by running pip3 install -r ts3/requirements.txt. 

The second step should fix your problem. If it doesn't feel free to reopen the issue.
