### ISSUE TITLE
losing connection

### ISSUE THREAD

**Issue by PonyDevil** [Murgeye/teamspeak3-python-bot#4]
```
2018-09-17 16:25:25,433: INFO: Started
2018-09-17 16:30:25,452: ERROR: Uncaught exception.
Traceback (most recent call last):
  File "/opt/teamspeak3-python-bot/ts3/TS3Connection.py", line 144, in _recv
    resp = self._tel_conn.read_until(b"\n\r")[:-2]
  File "/usr/lib/python3.4/telnetlib.py", line 329, in read_until
    return self.read_very_lazy()
  File "/usr/lib/python3.4/telnetlib.py", line 405, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 42, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/teamspeak3-python-bot/ts3/TS3Connection.py", line 150, in _recv
    raise TS3Exception("Connection was closed!")
ts3.TS3Connection.TS3Exception: Connection was closed!
2018-09-17 16:30:40,687: ERROR: Uncaught exception.
Traceback (most recent call last):
  File "./main.py", line 42, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/teamspeak3-python-bot/ts3/TS3Connection.py", line 395, in keepal$
    self._send_keepalive()
  File "/opt/teamspeak3-python-bot/ts3/TS3Connection.py", line 386, in _send_$
    self._send("", wait_for_resp=False)
  File "/opt/teamspeak3-python-bot/ts3/TS3Connection.py", line 111, in _send
    self._tel_conn.write(query)
  File "/usr/lib/python3.4/telnetlib.py", line 292, in write
    self.sock.sendall(buffer)
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by Murgeye** [comment]
Hey,

hm, not a lot to go on here ... Just guessing into the blue, could it be that you did not whitelist the IP address your bot is connecting from?

> To do this change the file query-ip-whitelist.txt in the server directory and add a new line with your IP address.

Please let me know if this works for you!

**Comment by PonyDevil** [comment]
bot is running on same machine as server so connection is thrue local

**Comment by PonyDevil** [comment]
for me its look like its somthing wrong with keepalive function
bot get disconectet all the time in same period of time when it doing nothing

**Comment by Murgeye** [comment]
Are you by chance using a teamspeak server in version 3.4.0? I haven't updated my own server yet and did not try that version.

Could you post your `ts3server.ini` and possibly any server log message from `logs/ts3server_0.log` that relate to query?

> bot is running on same machine as server so connection is thrue local

We had to add 127.0.0.1 to the query-ip-whitelist.txt file, but if that was the issue it should not be able to connect after disconnecting the first time.

**Comment by PonyDevil** [comment]
its not issue with whitelist :) im runing 3.4.0 i prepare logs for you give me couple of minuts

**Comment by PonyDevil** [comment]
okey some more info after starting afkmodule bot is on server without disconecting. its posible that keepalive is not starting?

**Comment by Murgeye** [comment]
At least for me, it is sending keepalive messages every five seconds. But I can now reproduce the issue with a test setup of the new server. I _think_ that the Teamspeak devs might have changed the reaction to empty messages. Basically the timeout until now is to just send `\r\n` and that was enough. 

I will do some tests and get back to you.

Activating the afkmover is of course not the desired solution but will increase the frequency of messages a lot probably preventing the timeout.

**Comment by PonyDevil** [comment]
thanks keep up nice work:D i will for sure write up some modules:)

**Comment by Murgeye** [comment]
What should also work as a temporary workaround is setting `query_timeout=0` in the `ts3server.ini`. This should make the keepalive obsolete. 

I will update the API to use the `whoami` command as a keep alive to fix this for now, after I tested that for a bit. This is not ideal, so better ideas are welcome :)

Thanks for bringing that issue up!

**Comment by Murgeye** [comment]
Should be fixed now, thanks again.

If any issues remain please feel free to reopen this issue or open a new one.
