### ISSUE TITLE
Get ClientDB ID

### ISSUE THREAD

**Issue by 1nexis** [Murgeye/teamspeak3-python-bot#8]
I'm probably pretty stupid, but is there a way to get the cldbid like the client id as "sender" ?

**Comment by Murgeye** [comment]
I am not completely sure what you are trying to do. If you have the client id already you can get the client database id by requesting the clientInfo:

```
client_data = bot.ts3conn.clientinfo(client_id)
database_id = client_data.get('client_database_id')
```

If this does not help you please feel free to ask!

**Comment by 1nexis** [comment]
Just trying to get a command to give a user a certain server group by tiping the server groups name as a command. 
like: !registered > give the user the server group registered

**Comment by Murgeye** [comment]
I would probably do something like this:

```
from ClientInfo import ClientInfo
@command('register',)
def register_client(sender, msg):
    client = ClientInfo(sender, bot.ts3conn)
    database_id = client._database_id
    if not client.is_in_servergroups("Registered"):
        sgl = bot.ts3conn.servergrouplist()
        for sg in sgl:
            if sg["name"] == "Registered":
                sgid = sg["sgid"]
        bot.ts3conn.servergroupaddclient(sgid=sgid, cldbid=database_id)
```
This will of course fail if the Registered group does not exist.

The ClientInfo class wasn't updated for some time, I guess I will change it to expose the properties it contains when I find the time. Also I should probably implement a `get_servergroup(pattern)` function for cases like this so iterating through the list is not necessary.

Does this help you?

**Comment by 1nexis** [comment]
Yes thanks alot!

**Comment by Murgeye** [comment]
Thanks for asking, I managed to find another (simple) bug by testing your command!

I am closing this, feel free to open another Issue when you have more questions!
