### ISSUE TITLE
Bot is running but invisible and not responding

### ISSUE THREAD

**Issue by ctrl-Felix** [Murgeye/teamspeak3-python-bot#9]
I installed the bot and started it. When I go on the Server Info it says 2 Clients connected, me and the bot. But I can't see the bot and if I type commands like !whoami nothing happens. The Bot log gives me:
```2020-04-03 17:51:05,981: INFO: Started```

**Comment by Murgeye** [comment]
Hey Felix,

Have you done what's mentioned in the readme under permissions? Otherwise you will not be able to see and talk to the client. Additionally, you have to check this in your client settings: https://image.gametracker.com/news/2013/12/17_50_06.png

Commands will only work as direct messages to the bot.

**Comment by Murgeye** [comment]
I have updated the troubleshooting section of the readme with these steps. Do these resolve your problem?

**Comment by ctrl-Felix** [comment]
Sorry for the late response, I did it but it did not fiy my problem. Anyway I think I misconfigured it, as it shows me 0 Client connected to the Channel where the bot should be. In the logs I get ```The bot is already in the configured default channel```

**Comment by Murgeye** [comment]
No worries. The bot is "he bot is already in the configured default channel" usually just means that the channel the bot joined the server in is the same as the channel configured in the config.ini.

This does, however, not prevent the bot from running (this is just an informational message for debugging). Do you see the bot for a short time when it joins the server? Maybe it's getting kicked from the server instantly. If you could post the last entries in the server log, that would be useful.

What value did you set the i_client_serverquery_view_power (a) permission to on your user/group? Also check the i_client_needed_serverquery_view_power (b) on the serverquery group please. (a) should be greater that (b) for you to be able to see the bot.

**Comment by ctrl-Felix** [comment]
I found the solution by going through the setup again, I don't know why it did not work.

Thanks for the help

**Comment by Murgeye** [comment]
Alright, thanks for your feedback. Feel free to ask if you have more issues.
